# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
luau-lsp = "Quenty/luau-lsp@1.58.0-quenty.1"
lune = "lune-org/lune@0.8.9"
mantle = "blake-mealey/mantle@0.10.7"
moonwave-extractor = "UpliftGames/moonwave@1.3.0"
remodel = "rojo-rbx/remodel@0.9.1"
rojo = "quenty/rojo@7.7.0-rc.1-quenty.4"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
selene = "Kampfkarren/selene@0.29.0"
stylua = "johnnymorganz/stylua@2.3.1"
