[tools]
rojo = { github = "quenty/rojo", version = "=7.4.3-quenty-npm-canary.2" }
luau-lsp = { github = "quenty/luau-lsp", version = "=1.58.0-quenty.1" }
stylua = { github = "johnnymorganz/stylua", version = "=2.1.0" }