[tools]
rojo = { github = "quenty/rojo", version = "=7.7.0-rc.1-quenty.3" }
luau-lsp = { github = "quenty/luau-lsp", version = "=1.58.0-quenty.1" }
stylua = { github = "johnnymorganz/stylua", version = "=2.3.1" }