[tools]
rojo = { source = "quenty/rojo", version = "=7.0.0-quenty-npm-canary.4" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
selene = { source = "Kampfkarren/selene", version = "0.14.0" }
moonwave-extractor = { source = "UpliftGames/moonwave", version="^0.3.3" }
mantle = { source = "blake-mealey/mantle", version = "0.10.7" }