name: build
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          version: 'v0.2.7'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate standard library
        run: selene generate-roblox-std

      - name: Run Selene
        run: selene src

      - name: Run moonwave-extractor
        if: success() || failure()
        run: moonwave-extractor extract src