# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman
[tools]
rojo = "quenty/rojo@7.4.0-quenty-npm-canary.1"
selene = "Kampfkarren/selene@0.25.0"
moonwave-extractor = "UpliftGames/moonwave@1.0.1"