# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman
[tools]
rojo = "quenty/rojo@7.4.3-quenty-npm-canary.1"
selene = "Kampfkarren/selene@0.26.1"
moonwave-extractor = "UpliftGames/moonwave@1.1.2"