# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman
[tools]
rojo = "quenty/rojo@7.2.1-quenty-npm-canary.5"
selene = "Kampfkarren/selene@0.24.0"