name: linting
on: [pull_request, workflow_call]
jobs:
  luau-lsp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: 'v0.3.0'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          cache: true

      - name: Setup npm for GitHub Packages
        run: |
          echo -e "\n//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
          echo -e "\n//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> ~/.npmrc
          echo -e "\n//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          echo -e "\n//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all tools
        run: pnpm -r --filter './tools/**' --filter '!./tools/nevermore-vscode' run build

      - name: Install nevermore-cli locally
        run: npm install --ignore-scripts -g .
        working-directory: tools/nevermore-cli

      - name: Generate Sourcemap
        run: npm run build:sourcemap

      - name: luau-lsp analyze
        run: npm run lint:luau

  stylua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: 'v0.3.0'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: true

      - name: stylua check
        run: npm run lint:stylua

  selene:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: 'v0.3.0'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: true

      - name: selene check
        run: npm run lint:selene

  moonwave:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: 'v0.3.0'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: true

      - name: Run moonwave-extractor
        run: npm run lint:moonwave
